openapi: 3.0.3
info:
  title: Carton Caps Referral API
  description: |
    This is a full technical description of the endpoints (backend API) for the referral app called
    Carton Caps. This definition serves double purpose: 1. for the backend to implement a clear goal, 2. for the clients to know and understand how to use the api.
    In other words, this is a contract for the backend to implement and for the client (or frontend) to use.
  version: v1
servers:
- url: /api
  description: GA API base path
- url: /beta
  description: Staging experimental API base path
paths:
  /ping:
    get:
      tags:
      - Health
      summary: Is the API running?
      description: A simple endpoint to check the liveliness of the service.
      responses:
        "200":
          description: Service is running
          content:
            text/plain:
              schema:
                type: string
                example: pong
                enum:
                - pong
      servers:
      - url: /api
        description: Available in GA API only
components:
  schemas: {}
